### ISSUE TITLE
No tag found that was able to satisfy *

### ISSUE THREAD

**Issue by jplatte** [purescript/purescript-psci-support#1]
I was just trying out psc 0.9.0 and got this error when trying to install `purescript-psci-support` for psci. I guess bower doesn't recognize `1.0.0-rc.1` as valid semver or something like that. Maybe removing the dot after the `rc` would help?

EDIT: Also, trying to manually select the `1.0.0-rc.1` tag, I get the same kind of error about `purescript-console`:

```
% bower install 'purescript-psci-support#1.0.0-rc.1'                                                                                                                                         :(
bower purescript-psci-support#1.0.0-rc.1       not-cached https://github.com/purescript/purescript-psci-support.git#1.0.0-rc.1
bower purescript-psci-support#1.0.0-rc.1          resolve https://github.com/purescript/purescript-psci-support.git#1.0.0-rc.1
bower purescript-psci-support#1.0.0-rc.1         checkout v1.0.0-rc.1
bower purescript-psci-support#1.0.0-rc.1         resolved https://github.com/purescript/purescript-psci-support.git#1.0.0-rc.1
bower purescript-console#^1.0.0                not-cached https://github.com/purescript/purescript-console.git#^1.0.0
bower purescript-console#^1.0.0                   resolve https://github.com/purescript/purescript-console.git#^1.0.0
bower purescript-console#^1.0.0              ENORESTARGET No tag found that was able to satisfy ^1.0.0

Additional error details:
Available versions in https://github.com/purescript/purescript-console.git: 1.0.0-rc.1, 0.1.1, 0.1.0, 0.1.0-rc.1
```

**Comment by paf31** [comment]
Could you try now please?

**Comment by jplatte** [comment]
Still the same error. With the slight change that there is one more available version now, but it still can't match that with the implicit version `*` (whoever decided that that wouldn't be a literal 'any version'...)

EDIT: If I select the latest version manually now though, it works.

**Comment by paf31** [comment]
If I put `^1.0.0-rc.1` in `bower.json` for this library, it installs fine.

**Comment by jplatte** [comment]
Well `1.0.0-rc.2` probably matches `^1.0.0-rc.1`. But it doesn't match `*`, and that's what bower looks for with a plain `bower install purescript-psci-support` without a version attached. Also, by the way, do I need a newer version of `pulp` to build projects with psc 0.9.0? I get `Invalid option `--ffi'` when trying to build right now.

**Comment by paf31** [comment]
Yes, Pulp hasn't been released yet. You won't be able to install that way, since the library is not released yet. I understand that's what psci recommends, but it's only until we get everything updated and the RC out the door.

**Comment by jplatte** [comment]
Alright, so is it just desired behaviour that `bower install purescript-psci-support` doesn't install rcs? If so, I don't mind this issue being closed.

**Comment by paf31** [comment]
Yes, I think so. This will be sorted out soon.
