### ISSUE TITLE
PureScript 0.12.0 - Overlapping type class instances found for PSCI.Support.Eval (Eff eff a)

### ISSUE THREAD

**Issue by rouanvd** [purescript/purescript-psci-support#10]
Error 7 of 7:

  in module PSCI.Support
  at bower_components\purescript-psci-support\src\PSCI\Support.purs line 23, column 1 - line 23, column 47

    Overlapping type class instances found for

      PSCI.Support.Eval (Eff eff a)

    The following instances were found:

      PSCI.Support.evalShow
      PSCI.Support.evalEff

  in type class instance

    PSCI.Support.Eval (Eff eff a)

  See https://github.com/purescript/documentation/blob/master/errors/OverlappingInstances.md for more information,
  or to contribute content related to this error.

**Comment by garyb** [comment]
Yeah, we're working on releasing the libraries for 0.12 at the moment. The next release of `purescript-psci-support` will fix this.

**Comment by rouanvd** [comment]
No problem :)
Maybe I am just too eager.  I will wait a bit before upgrading to 0.12.

Thanks Gary.

**Comment by garyb** [comment]
Intending to get the core libraries out today, so hopefully you shouldn't have to wait too long! 🙂
