### ISSUE TITLE
Eval instance for Aff

### ISSUE THREAD

**Issue by srghma** [purescript/purescript-psci-support#16]
is it possible?

**Comment by hdgarrood** [comment]
It’s not possible. This is a core library and Aff isn’t, and core libraries may only depend on other core libraries.

**Comment by hdgarrood** [comment]
The instance would have to be defined in aff, not here.

**Comment by natefaubion** [comment]
> The instance would have to be defined in aff, not here.

Note that this isn't possible with the default `eval` method due to the catch all instance chain. One would need to override this with the `:print` directive.

**Comment by hdgarrood** [comment]
Oh of course, yes.
