### ISSUE TITLE
Overlap issues in 0.10?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-psci-support#2]
@paf31 Is there still a problem here, or was it fixed during the revisions to the fundeps branch? It doesn't seem to warn at definition time, so maybe it's ok now?

**Comment by paf31** [comment]
Overlaps are resolved during instance search, so there is still a warning. PSCi doesn't show warnings, so there is no message shown in PSCi, but there is if you compile this library as a regular dependency.

I would like to remove the overlap, but it's not clear how to do it. Maybe there is some clever trick, but I've yet to find it.

**Comment by garyb** [comment]
I guess this is like the thing I wanted to do with `Invariant`. I assume there's no reasonable chance of preventing instance search from committing unless constraints are satisfied too?

**Comment by LiamGoodacre** [comment]
Solved with instance chains in the above PR.
