### ISSUE TITLE
:browse Prim does not work

### ISSUE THREAD

**Issue by marick** [purescript/purescript-psci-support#4]
The Purescript book says that primitive types are defined in the `Prim` module. So I wanted to see what functions were available. I can import `Prim`:

```
> import Prim
```

But `:browse` doesn't work:

```
> :browse Prim
Module 'Prim' is not valid.
```

That's the same message as for a completely bogus module. Why this message? If it's because `Prim` is somehow magic, should that be made clear?

**Comment by paf31** [comment]
Please file this as a compiler bug, thanks.
