### ISSUE TITLE
Rename to `purescript-repl-support`?

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-psci-support#6]
Since `psci` doesn't exist anymore.

**Comment by paf31** [comment]
I think `purs repl` still says "PSCi" after launching. I think it's fine to say "_the_ REPL is PSCi" and to continue using both terms, no?

**Comment by natefaubion** [comment]
So I guess we should rename "PSCi" then? 😛

**Comment by paf31** [comment]
To what?

**Comment by natefaubion** [comment]
It's strange to continue to refer to it as `psci` when you don't invoke it via the `psci` command. Likewise referring to the compiler as `psc`. They are all just `purs` or `PureScript` /shrug.

**Comment by paf31** [comment]
I guess so, but I think it's reasonable to continue calling it PSCi, for lack of another name, instead of just the generic "the REPL" 😄

**Comment by natefaubion** [comment]
Fair enough :)
